image: python:3.8

stages:
  - test
  - coverage
  - deploy

before_script:
  - pip install --upgrade pip
  - pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib
  - pip install coverage
  - pip install python-dateutil

test:
  stage: test
  script:
     python CalendarTest.py

coverage:
  stage: coverage
  script:
    - coverage run -m CalendarTest
    - coverage report
    - coverage html
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    paths:
      - htmlcov/


pages:
    stage: deploy
    dependencies:
        - coverage
    script:
        - mv htmlcov/ cov_html/
    artifacts:
        paths:
            - cov_html/
    only:
      - master